version: "3.9"
name: "desafio-v1"

services:
  spring-api1:
    build:
      context: './spring-boot-api'
      dockerfile: Dockerfile.arm
    hostname: spring-api1
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=jdbc:postgresql://db-postgresql:5432/desafiodb
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - db-postgresql
    ports:
      - "8080:8080"
    networks:
      - app-network

  web: 
    build: './angular-app'
    ports: 
      - 80:80
    depends_on:
      - spring-api1
    networks:
      - app-network

  db-postgresql:
    image: postgres:latest
    command: "postgres -c max_connections=200 -c shared_buffers=256MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off"
    hostname: db-postgresql
    volumes:
      - ./spring-boot-api/database/migrate.sql:/docker-entrypoint-initdb.d/migrate.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafiodb
    networks:
      - app-network

networks:
  app-network:
