version: "3.9"
name: "desafio-v1"

services:
  spring-api1:
    build: .
    hostname: spring-api1
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=r2dbc:postgresql://db-postgresql:5432/desafiodb
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - REDIS_HOST=cache
    depends_on:
      - db-postgresql
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "1GB"
    networks:
      - app-network


  db-postgresql:
    image: postgres:latest
    command: "postgres -c max_connections=200 -c shared_buffers=256MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off"
    hostname: db-postgresql
    volumes:
      - ./migrate.sql:/docker-entrypoint-initdb.d/migrate.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafiodb
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1GB"
    networks:
      - app-network

networks:
  app-network:
